version: '3'

name: example-agent-1

services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    #restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - default

  promtail:
    image: grafana/promtail:2.6.1
    container_name: promtail
    #restart: unless-stopped
    volumes:
      - /var/log/journal/:/var/log/journal/
      - /run/log/journal/:/run/log/journal/
      - /etc/machine-id:/etc/machine-id
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail/config/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - default

networks:
  default:
    name: monitoring-network